# Generated by Django 5.1.15 on 2026-06-30 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto (USD)')),
                ('method', models.CharField(choices=[('CASH_USD', 'Efectivo (USD)'), ('CASH_BS', 'Efectivo (Bs)'), ('MOBILE', 'Pago Móvil'), ('TRANSFER', 'Transferencia'), ('CARD', 'Punto de venta')], default='MOBILE', max_length=10, verbose_name='Método')),
                ('currency', models.CharField(choices=[('BCV', 'Bs (BCV)'), ('CASH', 'Divisas ($)')], default='BCV', max_length=4, verbose_name='Moneda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='client.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='plans.plan')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
