# Generated by Django 5.1.15 on 2026-07-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='Personalizado'),
        ),
    ]
