# Generated by Django 5.1.15 on 2026-07-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_is_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH_USD', 'Efectivo (USD)'), ('ZELLE', 'Zelle'), ('BINANCE', 'Binance'), ('CASH_BS', 'Efectivo (Bs)'), ('MOBILE', 'Pago Móvil'), ('TRANSFER', 'Transferencia'), ('CARD', 'Punto de venta')], default='MOBILE', max_length=10, verbose_name='Método'),
        ),
    ]
