# Generated by Django 5.1.15 on 2026-07-07 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='trainer',
            field=models.ForeignKey(blank=True, help_text='Solo para planes diarios (no generan membresía propia).', limit_choices_to={'roles__contains': ['INSTRUCTOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_as_trainer', to=settings.AUTH_USER_MODEL, verbose_name='Entrenador'),
        ),
    ]
