# Generated by Django 5.1.15 on 2026-07-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vence el plan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio del plan'),
        ),
    ]
