# Generated by Django 5.1.15 on 2026-06-30 23:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Zona Gym', max_length=120, verbose_name='Nombre')),
                ('bcv_rate', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=10, verbose_name='Tasa BCV (Bs/USD)')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='RIF')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
    ]
