# Generated by Django 5.1.15 on 2026-07-02 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True, verbose_name='Fecha')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tasa (Bs/USD)')),
                ('source', models.CharField(choices=[('AUTO', 'Automática (BCV)'), ('MANUAL', 'Manual')], default='AUTO', max_length=6, verbose_name='Origen')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'verbose_name_plural': 'Tasas de cambio',
                'ordering': ['-date'],
            },
        ),
    ]
