# Generated by Django 5.1.15 on 2026-07-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_exchangerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymconfig',
            name='bcv_rate',
        ),
    ]
