# Generated by Django 5.1.15 on 2026-06-30 23:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('id_card', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('FROZEN', 'Congelado'), ('OVERDUE', 'Moroso')], default='ACTIVE', max_length=10, verbose_name='Estado')),
                ('health', models.CharField(blank=True, max_length=200, verbose_name='Datos de salud')),
                ('emergency_contact', models.CharField(blank=True, max_length=160, verbose_name='Contacto de emergencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Freeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=160, verbose_name='Motivo')),
                ('days', models.PositiveIntegerField(verbose_name='Días')),
                ('start_date', models.DateField(verbose_name='Desde')),
                ('end_date', models.DateField(verbose_name='Hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezes', to='client.client')),
            ],
            options={
                'verbose_name': 'Congelación',
                'verbose_name_plural': 'Congelaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Vence')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Personalizado')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto pagado (USD)')),
                ('currency', models.CharField(choices=[('BCV', 'Bs (BCV)'), ('CASH', 'Divisas ($)')], default='BCV', max_length=4, verbose_name='Moneda')),
                ('days', models.PositiveIntegerField(default=0, verbose_name='Días')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='client.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='plans.plan')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
            },
        ),
    ]
