# Generated by Django 5.1.15 on 2026-07-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_normalize_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeze',
            name='kind',
            field=models.CharField(choices=[('DAYS', 'Días'), ('MONTHS', 'Meses'), ('INDEFINITE', 'Indefinido')], default='DAYS', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días'),
        ),
        migrations.AlterField(
            model_name='freeze',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hasta'),
        ),
    ]
