# Generated by Django 5.1.15 on 2026-07-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_freeze_kind_alter_freeze_days_alter_freeze_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='doc_type',
            field=models.CharField(choices=[('V', 'V - Venezolano'), ('E', 'E - Extranjero'), ('J', 'J - Jurídico'), ('P', 'P - Pasaporte')], default='V', max_length=1, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_card',
            field=models.CharField(max_length=20, verbose_name='Cédula'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('doc_type', 'id_card'), name='client_unique_doc_id', violation_error_message='Ya existe un cliente con ese tipo y número de documento.'),
        ),
    ]
