# Generated by Django 5.1.15 on 2026-07-04 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_created_by_freeze_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__contains': ['INSTRUCTOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_as_trainer', to=settings.AUTH_USER_MODEL, verbose_name='Entrenador'),
        ),
    ]
