# Generated by Django 5.1.15 on 2026-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_membership_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('FROZEN', 'Congelado'), ('OVERDUE', 'Moroso'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=10, verbose_name='Estado'),
        ),
    ]
