# Generated by Django 5.1.15 on 2026-07-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inactivo desde'),
        ),
    ]
