# Generated by Django 5.1.15 on 2026-06-30 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Opcional · nómbralo solo en combos', max_length=120, verbose_name='Nombre')),
                ('duration', models.CharField(choices=[('DAILY', 'Diaria'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual')], default='MONTHLY', max_length=10, verbose_name='Duración')),
                ('price_bcv', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio pagando en Bs (USD)')),
                ('price_cash', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio en divisas/efectivo $ (USD)')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Personalizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('included_services', models.ManyToManyField(blank=True, related_name='included_in', to='services.service', verbose_name='Áreas incluidas')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='services.service')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['service__name', 'duration'],
            },
        ),
    ]
