# Generated by Django 5.1.15 on 2026-06-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('color', models.CharField(default='#343959', max_length=7, verbose_name='Color')),
                ('kind', models.CharField(choices=[('OPEN', 'Acceso libre'), ('GUIDED', 'Clase dirigida'), ('MIXED', 'Mixto / combos')], default='OPEN', max_length=10, verbose_name='Tipo')),
                ('requires_trainer', models.BooleanField(default=False, help_text='Marca Boxeo/MMA: exige asignar entrenador en la membresía', verbose_name='Requiere entrenador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['name'],
            },
        ),
    ]
