# Generated by Django 5.1.15 on 2026-07-03 04:58

from django.db import migrations, models


def copy_discipline_to_disciplines(apps, schema_editor):
    User = apps.get_model("user", "User")
    for user in User.objects.exclude(discipline_id=None):
        user.disciplines.add(user.discipline_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='instructors_tmp', to='services.service', verbose_name='Disciplinas que enseña'),
        ),
        migrations.RunPython(copy_discipline_to_disciplines, noop),
        migrations.RemoveField(
            model_name='user',
            name='discipline',
        ),
        migrations.AlterField(
            model_name='user',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='services.service', verbose_name='Disciplinas que enseña'),
        ),
    ]
