# Generated by Django 5.1.15 on 2026-07-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_normalize_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doc_type',
            field=models.CharField(choices=[('V', 'V - Venezolano'), ('E', 'E - Extranjero'), ('J', 'J - Jurídico'), ('P', 'P - Pasaporte')], default='V', max_length=1, verbose_name='Tipo de documento'),
        ),
    ]
