# Generated by Django 5.1.15 on 2026-06-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FIXED', 'Fija'), ('CUSTOM', 'Personalizada')], default='FIXED', max_length=10, verbose_name='Tipo')),
                ('day', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')], verbose_name='Día')),
                ('block', models.CharField(choices=[('8:40-10:30 am', '8:40-10:30 am'), ('9:00-11:00 am', '9:00-11:00 am'), ('2:40-3:50 pm', '2:40-3:50 pm'), ('6:00-7:00 pm', '6:00-7:00 pm'), ('7:00-8:00 pm', '7:00-8:00 pm'), ('8:00-9:00 pm', '8:00-9:00 pm'), ('9:00-10:00 pm', '9:00-10:00 pm')], max_length=20, verbose_name='Bloque horario')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['day', 'block'],
            },
        ),
    ]
