# Generated by Django 5.1.15 on 2026-06-30 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='classes_as_main', to=settings.AUTH_USER_MODEL, verbose_name='Entrenador'),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='second_instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_as_second', to=settings.AUTH_USER_MODEL, verbose_name='Segundo entrenador'),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='service',
            field=models.ForeignKey(limit_choices_to={'kind': 'GUIDED'}, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='services.service', verbose_name='Clase dirigida'),
        ),
    ]
