# Generated by Django 5.1.15 on 2026-07-04 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_gymclass_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'roles__contains': ['INSTRUCTOR']}, on_delete=django.db.models.deletion.PROTECT, related_name='classes_as_main', to=settings.AUTH_USER_MODEL, verbose_name='Entrenador'),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='second_instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__contains': ['INSTRUCTOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_as_second', to=settings.AUTH_USER_MODEL, verbose_name='Segundo entrenador'),
        ),
    ]
